name: Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - {django: '==4.2.*', python: '3.11'}
          - {django: '==4.2.*', python: '3.10'}
          - {django: '==4.2.*', python: '3.9'}
          - {django: '==4.2.*', python: '3.8'}

          - {django: '~=4.1.3', python: '3.11'}
          - {django: '==4.1.*', python: '3.10'}
          - {django: '==4.1.*', python: '3.9'}
          - {django: '==4.1.*', python: '3.8'}

          - {django: '==4.0.*', python: '3.10'}
          - {django: '==4.0.*', python: '3.9'}
          - {django: '==4.0.*', python: '3.8'}

          - {django: '~=3.2.9', python: '3.10'}
          - {django: '==3.2.*', python: '3.9'}
          - {django: '==3.2.*', python: '3.8'}

          - {django: '~=3.1.3', python: '3.9'}
          - {django: '==3.1.*', python: '3.8'}

          - {django: '~=3.0.11', python: '3.9'}
          - {django: '==3.0.*', python: '3.8'}

          - {django: '~=2.2.17', python: '3.9'}
          - {django: '~=2.2.8', python: '3.8'}
    steps:
      - uses: actions/checkout@v3
      - run: pipx install poetry==1.4.0
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: 'poetry'
      - run: poetry run pip install --pre 'django${{ matrix.django }}'
      - run: poetry install --no-interaction --with=dev
      - run: poetry run pytest -vv
